### ISSUE TITLE
Broken Buttons: prioritise third row over second for Twitch Plays.

### ISSUE THREAD

**Issue by AndrioCelos** [samfun123/KTANE-Mods#16]
There have been mistakes made with this module on Twitch Plays where the third row had a T-word which was also duplicated in the second row. Entering `!# press "TWO"` pressed the one on the second row, which is wrong. Is it worth changing this?

**Comment by samfun123** [comment]
It's not worth changing because you can specify a button by it's position. People do need to be careful when they need to hit a specific button.
